/*
 * This source file was generated by the Gradle 'init' task
 */
package ar.edu.austral.inf.sd

import ar.edu.austral.inf.sd.App
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertNotNull

class AppTest {
    @Test
    fun appHasAGreeting() {
        val classUnderTest = App()
//        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
